In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Name : {torch.cuda.get_device_name()}")
else:
  print("GPU is not available")

GPU is available
Name : Tesla T4


#### Allocate space , the values that are showing are garbage values

In [3]:
torch.empty(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.zeros(1,4)

tensor([[0., 0., 0., 0.]])

In [6]:
torch.rand(2,3)

tensor([[0.2971, 0.6229, 0.2235],
        [0.8639, 0.0999, 0.2027]])

#### define a random seed

In [7]:
torch.manual_seed(100)

In [8]:
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [10]:
torch.tensor([[1,23,4],[23,4,5]])

tensor([[ 1, 23,  4],
        [23,  4,  5]])

In [11]:
torch.arange(0,11,2)

tensor([ 0,  2,  4,  6,  8, 10])

In [12]:
torch.linspace(0,11,4)

tensor([ 0.0000,  3.6667,  7.3333, 11.0000])

In [13]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.empty_like(x)

tensor([[133182640881670,       162430608,     64424510548],
        [      162430480,               6,       162430640]])

In [18]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor data types


In [19]:
x.dtype

torch.int64

In [20]:
x = torch.tensor([1,23,4],dtype=torch.int32) # you have to specify the dtype as rand generates values btw 0 - 1 and x has int values

In [21]:
x.to(torch.float32)

tensor([ 1., 23.,  4.])

### Arithmatic Operations

In [22]:
x + 2

tensor([ 3, 25,  6], dtype=torch.int32)

In [23]:
x - 2

tensor([-1, 21,  2], dtype=torch.int32)

In [24]:
x * 2

tensor([ 2, 46,  8], dtype=torch.int32)

In [25]:
x / 2

tensor([ 0.5000, 11.5000,  2.0000])

In [26]:
x % 2

tensor([1, 1, 0], dtype=torch.int32)

In [27]:
## similarly we can perform operations on the two tensors

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
x*y

tensor([ 4, 10, 18])

In [28]:
x = torch.negative(x)
x

tensor([-1, -2, -3])

In [29]:
torch.abs(x)

tensor([1, 2, 3])

In [30]:
x = torch.tensor([1.33,2.666,3.444,5.66666])
print(torch.ceil(x))
print(torch.floor(x))


tensor([2., 3., 4., 6.])
tensor([1., 2., 3., 5.])


In [31]:
torch.clamp(x,min=2,max=3)

tensor([2.0000, 2.6660, 3.0000, 3.0000])

In [32]:
torch.randint(size=(4,3),low=3,high=8)

tensor([[6, 6, 7],
        [7, 4, 3],
        [7, 6, 6],
        [5, 7, 4]])

In [33]:
torch.sum(torch.randint(size=(4,3),low=3,high=8))

tensor(56)

In [34]:
## sum along cols
torch.sum(torch.randint(size=(4,3),low=3,high=8),dim=0)

tensor([17, 20, 26])

In [35]:
## sum along rows
torch.sum(torch.randint(size=(4,3),low=3,high=8),dim=1)

tensor([18, 16, 16, 14])

In [37]:
y = torch.sum(torch.randint(size=(4,3),low=3,high=8),dim=0,dtype=torch.float32)
# torch.mean(y,dim=1) # works when data type of tensor is float|

In [42]:
x = torch.tensor([[1,23,4],[3,4,5]],dtype=torch.float32)
x

tensor([[ 1., 23.,  4.],
        [ 3.,  4.,  5.]])

In [43]:
y = torch.rand_like(x,dtype=torch.float32)
y

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

## Inplace Operations

In [44]:
# y = torch.tensor([])
x.add_(y)
x

tensor([[ 1.4393, 23.2243,  4.8935],
        [ 3.0497,  4.1780,  5.3011]])

In [45]:
y.relu_()

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

In [46]:
y

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

## Copying a tensor

In [48]:
## problem with normal assignment a = b is that even after assignment if b is changed then a will also change (they are at same memory location on is just a pointer)
new_copy = x.clone()
new_copy

tensor([[ 1.4393, 23.2243,  4.8935],
        [ 3.0497,  4.1780,  5.3011]])

## Tensor Operations on GPU

In [50]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name())

Tesla T4


>>> torch.device('cuda:0')
device(type='cuda', index=0)

>>> torch.device('cpu')
device(type='cpu')

>>> torch.device('mps')
device(type='mps')

(stands for metal performance shaders ,uses apple silicon chip(m1,m2,m3))

>>> torch.device('cuda')  # current cuda device
device(type='cuda')

In [51]:
## to create tensors on GUP
device = torch.device("cuda")

In [53]:
## make a new tensor on GPU

GPU_tensor = torch.zeros_like(x,device=device)

In [54]:
GPU_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [56]:
## convert a tensor from CPU to GPU
x.to(device)
## once a tensor is made on gpu all the operations on the tensor will be performed on the GPU
## operations on GPU will be much much more faster

tensor([[ 1.4393, 23.2243,  4.8935],
        [ 3.0497,  4.1780,  5.3011]], device='cuda:0')

## Reshaping Tensors

In [58]:
x = torch.rand(4,4,device=device)
x

tensor([[0.8344, 0.7001, 0.5361, 0.8883],
        [0.0220, 0.7938, 0.7543, 0.6514],
        [0.9609, 0.8294, 0.3537, 0.8665],
        [0.2563, 0.5770, 0.0433, 0.0837]], device='cuda:0')

In [59]:
x.reshape(2,2,2,2)

tensor([[[[0.8344, 0.7001],
          [0.5361, 0.8883]],

         [[0.0220, 0.7938],
          [0.7543, 0.6514]]],


        [[[0.9609, 0.8294],
          [0.3537, 0.8665]],

         [[0.2563, 0.5770],
          [0.0433, 0.0837]]]], device='cuda:0')

In [60]:
x.flatten()

tensor([0.8344, 0.7001, 0.5361, 0.8883, 0.0220, 0.7938, 0.7543, 0.6514, 0.9609,
        0.8294, 0.3537, 0.8665, 0.2563, 0.5770, 0.0433, 0.0837],
       device='cuda:0')

In [62]:
y = torch.rand(2,3,4,device = device)
y

tensor([[[0.1453, 0.6715, 0.8001, 0.4194],
         [0.1527, 0.4215, 0.1105, 0.0368],
         [0.4229, 0.2117, 0.9307, 0.2195]],

        [[0.0153, 0.3393, 0.1534, 0.2902],
         [0.0761, 0.1064, 0.0774, 0.5652],
         [0.6924, 0.1958, 0.2816, 0.2115]]], device='cuda:0')

In [64]:
y.permute(1,2,0).shape

torch.Size([3, 4, 2])

In [69]:
print(y.shape)
print(y.unsqueeze(0).shape)
print(y.unsqueeze(1).shape)
print(y.unsqueeze(2).shape)

torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 1, 3, 4])
torch.Size([2, 3, 1, 4])


In [70]:
torch.unsqueeze(y,0)

tensor([[[[0.1453, 0.6715, 0.8001, 0.4194],
          [0.1527, 0.4215, 0.1105, 0.0368],
          [0.4229, 0.2117, 0.9307, 0.2195]],

         [[0.0153, 0.3393, 0.1534, 0.2902],
          [0.0761, 0.1064, 0.0774, 0.5652],
          [0.6924, 0.1958, 0.2816, 0.2115]]]], device='cuda:0')

## Numpy to Pytorch

In [72]:
## torch tensor to numpy array
import numpy as np

A = torch.tensor([1,2,3,4,5])
B = A.numpy()
B

array([1, 2, 3, 4, 5])

In [73]:
A = np.array([1,2,3,4])
torch.from_numpy(A)

tensor([1, 2, 3, 4])